apiVersion: v1
kind: Service
metadata:
  labels:
    app: heal-redis
  name: redis-svc
  namespace: heal-app
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: heal-redis
  sessionAffinity: None
  type: ClusterIP